---
name: Rclone Backup
version: 1.2.0
slug: rclone_backup
description: Automatically sync backup to remote locations using rclone
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/jcwillox/hassio-rclone-backup
startup: application
boot: auto
map:
  - config:rw
  - backup:rw
  - share:ro
  - ssl:ro
  - media:ro
options:
  jobs:
    - name: Sync Daily Backups
      schedule: 0 4 * * *
      command: sync
      sources:
        - "/backup"
      destination: google:/Backup/Home Assistant
      include: []
      exclude: []
      flags: []
  dry_run: false
  config_path: "/config/rclone.conf"
schema:
  jobs:
    - name: str?
      schedule: str?
      command: str
      sources:
        - str
      destination: str
      include:
        - str
      exclude:
        - str
      flags:
        - str
  config_path: str
  rclone_config: str?
  run_once: bool?
  dry_run: bool?
  no_rename: bool?
  no_unrename: bool?
  log_level: list(debug|info|warning|error|fatal)?
image: ghcr.io/jcwillox/hassio-rclone-backup/{arch}
