name: 'Publish'

on:
  release:
    types: [published]

env:
  TARGET: rclone_backup

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Get addon information and update build args
      id: information
      uses: ./.github/actions/addon-info
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target ${{ env.TARGET }} \
          --image ${{ steps.information.outputs.image }} \
          --docker-hub ${{ steps.information.outputs.repository }}
